// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUJkiB14YnIVXPHntNPFEpryk5_ntfOw',
    appId: '1:254032794739:web:a7e976fccecf6dd97cc606',
    messagingSenderId: '254032794739',
    projectId: 'temp-1fe61',
    authDomain: 'temp-1fe61.firebaseapp.com',
    storageBucket: 'temp-1fe61.appspot.com',
    measurementId: 'G-TSXMHTYMCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnv0hvyGoqoQQOkaAunzfpisZ3KlTkOME',
    appId: '1:254032794739:android:8d7e6111ff1a2a6e7cc606',
    messagingSenderId: '254032794739',
    projectId: 'temp-1fe61',
    storageBucket: 'temp-1fe61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzjMlKH6ZnMXIcbfQ1nivq78c7MkpWmik',
    appId: '1:254032794739:ios:a1c9d2d7541a200f7cc606',
    messagingSenderId: '254032794739',
    projectId: 'temp-1fe61',
    storageBucket: 'temp-1fe61.appspot.com',
    iosBundleId: 'foodbridge.com.foodbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzjMlKH6ZnMXIcbfQ1nivq78c7MkpWmik',
    appId: '1:254032794739:ios:75e33bd9d8d4f1be7cc606',
    messagingSenderId: '254032794739',
    projectId: 'temp-1fe61',
    storageBucket: 'temp-1fe61.appspot.com',
    iosBundleId: 'foodbridge.com.foodbridge.RunnerTests',
  );
}
